id: P007007
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:35:50.643732
source_metadata:
  id: bdr:W30173
  title: གྲུབ་མཐའ་ཐུབ་བསྟན་ལྷུན་པོའི་མཛེས་རྒྱན།
  author: ''
  volumes:
    620a9d92602648b3a85fae1f31125c33:
      image_group_id: I1KG10577
      title: Volume 1 of grub mtha' thub bstan lhun po'i mdzes rgyan/
      volume_number: 1
      total_pages: 610
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
