id: P007007
initial_creation_type: ocr
source_metadata:
  id: bdr:W30173
  title: གྲུབ་མཐའ་ཐུབ་བསྟན་ལྷུན་པོའི་མཛེས་རྒྱན།
  author: ''
  volumes:
    132b36ce719e4c1e86c48fd8658bfd8e:
      image_group_id: I1KG10577
      title: ''
      volume_number: 1
      total_pages: 610
ebook_metadata:
  title: གྲུབ་མཐའ་ཐུབ་བསྟན་ལྷུན་པོའི་མཛེས་རྒྱན།
  author: ''
  sku: P007007
  cover: cover.jpg
  layers:
  - pagination
